Sumatorias, for y matrices
-------------------------------------


Descripción:
-----------------

A continuación se mostrarán algunos ejemplos con matrices de numpy que son muy útiles, como también de los usos de
las funciones *if* y *for* para manejarlas. Ya habíamos visto que se pueden crear matrices del tamaño que queramos de ceros, unos y números aleatorios de la siguiente forma

In [6]:
import numpy as np
import matplotlib.pyplot as plt

a = np.ones((4,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
b = np.zeros((5,4))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
c = np.random.rand(3,3)
print(c)

[[0.99270841 0.06362631 0.85268343]
 [0.96438669 0.78494388 0.04821629]
 [0.99955578 0.59802423 0.87318689]]


y que se pueden obtener los elementos de cada matriz así

-Elemento i,j de la matriz c: Fila i y columna j

In [11]:
print(c[1][2])

0.04821628857037308


-Vector fila i de c: En este caso especial el primer vector fila de c, es decir, el vector fila 0

In [13]:
print(c[0])

[0.99270841 0.06362631 0.85268343]


-Vector columna j de c: En este caso especial el primer vector columna de c, es decir, el vector columna 0

In [14]:
print(c[:,0])

[0.99270841 0.96438669 0.99955578]


Sin embargo, podemos ayudarnos de la función *for* para poder modificar los valores de las matrices que ya creamos, generar otras nuevas o hacer operaciones entre dos matrices distintas. Vamos a ver algunos ejemplos de cómo con *for* y matrices se pueden hacer muchas cosas.

Rellenar matriz con *for*
--------

Queremos, por ejemplo, transformar una matriz de ceros de $$m \times n$$ que creamos en una matriz cuyas entradas sean los números naturales desde el 1 hasta $$m \times n$$. Esto se hace de la siguiente forma:

In [15]:
n = 3
m = 4
A = np.zeros((n,m))
print(A)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
numero = 1
for i in range(0,n):
    for j in range(0,m):
        A[i][j] = numero
        numero = numero + 1
print(A)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


Multiplicar matrices con *for*
------

Las matrices, vistas como arrays de Python, también se pueden definir a partir de listas. Supongamos que queremos
encontrar la multiplicación de las siguientes matrices

\begin{equation*}
\begin{pmatrix}
1 & 2 & 3 \\
-1 & 3 & 0 \\
2 & 4 & 1
\end{pmatrix}\begin{pmatrix}
0 & 3 & 5 \\
5 & 4 & 2 \\
8 & 9 & 1
\end{pmatrix}
\end{equation*}

El resultado hecho a mano es

\begin{equation*}
\begin{pmatrix}
1 & 2 & 3 \\
-1 & 3 & 0 \\
2 & 4 & 1
\end{pmatrix}\begin{pmatrix}
0 & 3 & 5 \\
5 & 4 & 2 \\
8 & 9 & 1
\end{pmatrix} = \begin{pmatrix}
34 & 38 & 12 \\
15 & 9 & 1 \\
28 & 31 & 19
\end{pmatrix}
\end{equation*}

Esto sale de que, si A (de tamaño mxn) y B(de tamaño nxp) son las dos matrices que estamos multiplicando y C es el producto de A y B, entonces 

\begin{align*}
    C_{ij} = \sum_{k= 1}^{n} A_{ik}B_{kj}
\end{align*}

por lo que la implementación de la multiplicación de las matrices A y B se vería de la siguiente manera

In [18]:
A = np.array([[1.0,2.0,3.0],[-1.0,3.0,0.0],[2.0,4.0,1.0]])
B = np.array([[0.0,3.0,5.0],[5.0,4.0,2.0],[8.0,9.0,1.0]])
print(A)
print(B)

[[ 1.  2.  3.]
 [-1.  3.  0.]
 [ 2.  4.  1.]]
[[0. 3. 5.]
 [5. 4. 2.]
 [8. 9. 1.]]


In [23]:
C = np.zeros((3,3)) #Matriz que vamos a rellenar
print(C)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [24]:
for i in range(0,3):
    for j in range(0,3):
        for k in range(0,3):
            C[i][j] += A[i][k]*B[k][j]
print(C)

[[34. 38. 12.]
 [15.  9.  1.]
 [28. 31. 19.]]


Los dos *for* sobre i y j sirven para recorrer la matriz, como se hizo en el primer ejemplo, mientras que el *for* sobre k nos permite implementar la sumatoria para encontrar la componente i,j de la matriz C. El operador "+=" sirve para que, al valor de $C_{ij}$ anterior, se le sume en cada iteración el valor $A_{ik}B_{kj}$. Este *for* sobre la variable k es la implementación más común de una sumatoria. Por ejemplo, si queremos encontrar el valor de $S$ si

\begin{align*}
   S = \sum_{k=0}^{4} k^2
\end{align*}

Manualmente sabemos que 

\begin{align*}
   S = \sum_{k=0}^{4} k^2 = 0^2 + 1^2 + 2^2 + 3^2 + 4^2 = 0+ 1 + 4 + 9 + 16 = 30
\end{align*}

Pero si queremos implementar un programa que nos haga esta sumatoria entonces copiamos la forma del *for* visto anteriormente sobre la variable k.


In [28]:
S = 0
for k in range(0,5): #va de 0 a 5 porque k  va de 0 a n-1 si se pone range(0,n)
    S += pow(k,2)
print(S)

30


Como se observa, se obtiene el mismo resultado. Este *for* es la implementación estandar de una sumatoria en Python. También hay otra forma de obtener la multiplicación matricial. Como también se sabe, el elemento $C_{ij}$ se puede escribir como

\begin{align*}
    C_{ij} = A_{f_i} \cdot B_{c_j}
\end{align*}

donde $A_{f_i}$ es la fila i-esima de A y $B_{c_j}$ es la columna j-esima de B. Si hacemos esto nos ahorramos un *for* e incluso es más óptimo hacerlo de esta forma que con 3 ciclos *for*. Si lo hacemos de esta forma encontramos que llegamos a lo mismo

In [29]:
A = np.array([[1.0,2.0,3.0],[-1.0,3.0,0.0],[2.0,4.0,1.0]])
B = np.array([[0.0,3.0,5.0],[5.0,4.0,2.0],[8.0,9.0,1.0]])
C = np.zeros((3,3))

for i in range(0,3):
    for j in range(0,3):
        C[i][j] = np.dot(A[i],B[:,j]) #Producto punto entre la fila i de A y la columna j de B
print(C)

[[34. 38. 12.]
 [15.  9.  1.]
 [28. 31. 19.]]


De hecho, hay una forma más óptima de obtener directamente la multiplicación matricial y es con esta misma función np.dot()

In [30]:
A = np.array([[1.0,2.0,3.0],[-1.0,3.0,0.0],[2.0,4.0,1.0]])
B = np.array([[0.0,3.0,5.0],[5.0,4.0,2.0],[8.0,9.0,1.0]])
C = np.dot(A,B)
print(C)

[[34. 38. 12.]
 [15.  9.  1.]
 [28. 31. 19.]]


Pero era necesario explorar las ideas tras los ciclos *for* y las matrices para entender de donde provienen las cosas y entender algunos conceptos, como por ejemplo el de implementar sumatorias en Python.

Ejercicio
-------------

Implementar un código que encuentre el promedio, la desviación estandar y la varianza de los valores de una matriz $m \times n$ aleatoria.